### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by hollaus** [davidkun/HyperSpectralToolbox#1]
Hi,

thank you very much for your work, it's really helpful! 

I have found a few lines, where performance could be increased. In hyperCem a foor loop is used whereas you could use a vectorized form: 

results = target'_Rinv_M/tmp;

Again, thank you!

Regards
hofa

**Comment by davidkun** [comment]
Hey,

Thanks for the feedback! I implemented your suggestion. I didn't actually create that function, but based on the paper that it references, isn't that equation wrong?

Shouldn't it be more like:
`results = inv( target'*inv(R)*target ) * inv(R)*target`  ?

Here is **Equation 6** in the paper (_A Comparative Study for Orthogonal Subspace Projection and Constrained Energy Minimization_, by Qian Du) for comparison:

---

![screen shot 2015-01-06 at 12 35 17](https://cloud.githubusercontent.com/assets/2375234/5632984/18359456-95a1-11e4-97e9-6aa902cd2cb0.png)

---

I commented it out (for now), but this is how I would code **Equation 6** in `hyperCem.m`:

```
invRtarget = R_hat\target; % inv(R)*target
results    = ( target'*invRtarget ) \ invRtarget;
```

Let me know what you think.

Thanks,
David

**Comment by hollaus** [comment]
Hello, thanks for the fast answer.

Regarding your question: Both equations are the same - as far as I see.

In the current implementation the divisor is tmp:
tmp = target' \* Rinv \* target;
which is equal to 
inv( target' \* inv(R) \* target ) % from your post above.

The only difference is then the denominator, which is:
target' \* Rinv % current implementation
and
inv(R) \* target % from your post above

both versions give the same weight vector w, but the first one gives a row vector and the second one a column vector. So  the only difference is how you multiplicate the weight vector with the data. This must be:

results = w \* M % For the current implementation
or
results = w' \* M % For your post

So as far as I see, both versions are the same (I also tried it out).  However, I would prefer your solution, since it does not give any Matlab warnings that 'inv is slower than \'.

I hope that this is understandable.

Regards
hofa

**Comment by davidkun** [comment]
Thanks for your help!
I made those changes and added a couple of dimension checks at the beginning.

Best,
David
