### ISSUE TITLE
Error using dot 

### ISSUE THREAD

**Issue by M2ohamad** [davidkun/HyperSpectralToolbox#3]
Hello, thank you for sharing the hyperSam mapper function.

When I tried using it, I get the error below.
Error using dot
A and B must be the same size
Error in SAM
  angleAB(k) = acos(dot(tmp, B) / (norm(B) \* norm(tmp)));

A is a 1x144 vector and B is 13x144 vector. Is there anyway to get around using the dot command for two vectors of different sizes? Thank you.

**Comment by davidkun** [comment]
With your A and B matrices, it would work like this:
`err = hyperSam(B',A');`

I will change the function to be more smart about the dimensions of input vectors. In the meantime, you can use the above method to evaluate the angle error.

Thanks,
David

**Comment by davidkun** [comment]
I updated hyperSam to accept the 'row versions' of input vectors/matrices too, and made it so that the order doesn't matter as long as the dimensions match. 
e.g.

```
A = rand(1, 144);
B = rand(13, 144);

err1 = hyperSam(A , B);
err2 = hyperSam(A', B');
err3 = hyperSam(B , A);
err4 = hyperSam(B', A');

all(err1==err2) % ans = true
all(err2==err3) % ans = true
all(err3==err4) % ans = true
```

Thanks @M2ohamad !
