### ISSUE TITLE
hypermnf

### ISSUE THREAD

**Issue by Alessandroocc** [davidkun/HyperSpectralToolbox#5]
how can i implement hypermnf in demo?  I have done:
%% Resample AVIRIS image
[h, w, p] = size(M);
M2d = hyperConvert2d(M);
M = hyperMnf(M2d, h, w);
.......
but returns error :
Error using eig
Input to EIG must not contain NaN or Inf.

Error in eigs/fullEig (line 1086)
            [V,D] = eig(eigInputs{:});

Error in eigs (line 102)
    fullEig(nargout);

Error in hyperMnf (line 48)
[A, mu] = eigs(tmp, p);

Error in hyperDemo2 (line 54)
M = hyperMnf(M2d, h, w);

**Comment by davidkun** [comment]
There's probably something wrong with your input data (in your case, variable M).
As suggested in the README.md, download the Cuprite, Nevada hyperspectral image (HSI) from http://aviris.jpl.nasa.gov/data/free_data.html, and try again.
